# Generated by Django 2.2.7 on 2019-11-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(default='http://leeford.in/wp-content/uploads/2017/09/image-not-found.jpg', upload_to='images/'),
        ),
    ]
