# Generated by Django 2.2.7 on 2019-11-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(default='images/not-found.jpg', upload_to='images/'),
        ),
    ]
